spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/StreamWise

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

eureka.instance.preferIpAddress: true
eureka.client.registerWithEureka: true
eureka.client.fetchRegistry : true
eureka.client.serviceUrl.defaultZone: http://eurekaserver:8070/eureka/

spring.cloud.stream.bindings.output.destination: catalogChangeTopic
spring.cloud.stream.bindings.output.content-type: application/json
spring.cloud.stream.kafka.binder.zkNodes: kafka
spring.cloud.stream.kafka.binder.brokers: kafka

management.zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans
management.tracing.sampling.probability: 1.0

security.oauth2.resource.userInfoUri: http://authenticationservice:8082/user
security.oauth2.client.grant-type: client_credentials
signing.key: "345345fsdfsf5345"


keycloak.realm: StreamWise
keycloak.auth-server-url: http://keycloak:8080/
keycloak.ssl-required: external
keycloak.resource: streamwise
keycloak.credentials.secret: "**********"
keycloak.use-resource-role-mappings: true
keycloak.bearer-only: true

resilience4j:
  ratelimiter:
    instances:
      catalogService:
        limitForPeriod: 5
        limitRefreshPeriod: 5000
        timeoutDuration: 1000ms
  circuitbreaker:
    instances:
      catalogService:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 5
        ringBufferSizeInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
  bulkhead:
    instances:
      bulkheadCatalogService:
        maxWaitDuration: 2ms
        maxConcurrentCalls: 20
  thread-pool-bulkhead:
    instances:
      bulkheadCatalogService:
        maxThreadPoolSize: 1
        coreThreadPoolSize: 1
        queueCapacity: 1