spring:
  application:
    name: gateway-server
  config:
    import: configserver:http://configserver:8089/
    
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.price.streamwise: DEBUG
            