apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\makan\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\makan\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: database
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: streamwise
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres:16
          # livenessProbe:
          #   exec:
          #     command:
          #       - pg_isready -U postgres
          #   failureThreshold: 5
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          name: database
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/1-init.sql
              name: database-cm0
              subPath: 1-init.sql
            - mountPath: /docker-entrypoint-initdb.d/2-data.sql
              name: database-cm1
              subPath: 2-data.sql
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: init.sql
                path: 1-init.sql
            name: database-cm0
          name: database-cm0
        - configMap:
            items:
              - key: data.sql
                path: 2-data.sql
            name: database-cm1
          name: database-cm1
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
