apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\makan\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\makan\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: logstash
    spec:
      containers:
        - args:
            - logstash
            - -f
            - /etc/logstash/conf.d/logstash.conf
          image: docker.elastic.co/logstash/logstash:7.7.0
          name: logstash
          ports:
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/logstash/conf.d
              name: logstash-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: logstash-cm0
          name: logstash-cm0
