apiVersion: v1
data:
  logstash.conf: |-
    input {
      tcp {
        port => 5000
        codec => json_lines
      }
    }

    filter {
      mutate {
        add_tag => [ "%{application_name}" ]
      }
    }

    output {
      elasticsearch {
        hosts => "elasticsearch:9200"
      }
    }
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: logstash
  name: logstash-cm0
