server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      routes:
        - id: consumer-service
          uri: lb://consumer-service
          predicates:
            - Path=/consumer/**
          filters:
            - RewritePath=/consumer/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
          filters:
            - RewritePath=/catalog/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
