spring:
  application:
    name: configserver
  profiles:
    active:
      - git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/makani-rain/StreamWise.git
          default-label: main
          clone-on-start: true
          searchPaths: 
            - configs/{application}
    
server:
  port: 8071
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
